field: de9b26b0-3ac8-4473-b247-fe67f24d78dd
fieldLayouts:
  d9433d87-eaba-4287-86f0-59cff5b4d09f:
    tabs:
      -
        elements:
          -
            fieldUid: 23bde709-c2e0-473a-99e8-2f34ca4b503c # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  23bde709-c2e0-473a-99e8-2f34ca4b503c: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: bb97edd2-4089-4569-baa6-15e309da1d3f # Standard
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: false
      purifierConfig: ''
      purifyHtml: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: richText
name: 'Rich Text'
sortOrder: 1
