fieldLayouts:
  aafc28e5-a179-4d84-ac47-88b52cb4f37c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 4d377c00-46e0-43a3-9236-c87d82a888c9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4cfd6a68-1d9d-474d-9ca3-ef11450aa2bd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c2f8782c-80ac-4464-9669-cf04ed6e389d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: contactSubmissions
hasTitleField: false
name: 'Contact Submissions'
section: 23fe777d-796f-42ad-9816-87eebf91d39d
sortOrder: 1
titleFormat: '{nameInput}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
