fieldLayouts:
  059cf3a3-b3ec-4650-8823-2c0b971ee84c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 16e0e4bd-7977-4101-9f53-97ad62fd6f50
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23047120-5ec6-448e-b2ea-6525ca4a5a58
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 18e01b2e-58fc-4c77-9e95-52cebfba80e8 # Blog Categories
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
