fieldLayouts:
  d910dc15-da65-4b5d-bbc4-c7f1ac007bc7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: e391d82b-48b6-4ba5-ab0c-3b6f5ba7ab25
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: de9b26b0-3ac8-4473-b247-fe67f24d78dd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: b36df43f-70ae-497b-b307-b195c37c621e
            instructions: ''
            label: Category
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Meta
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 19d1e84a-6e8f-4958-b187-a3f7373915fd
            instructions: ''
            label: 'Featured Image'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: todayILearned
hasTitleField: true
name: 'Today I Learned'
section: 5e38ee1b-02f6-4954-aa92-36753faa2117
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
