contentColumnType: string
fieldGroup: a8521155-7afd-4462-b214-2c0909c7e927
handle: blogCategory
instructions: ''
name: 'Blog Category'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  maintainHierarchy: true
  selectionLabel: ''
  showSiteMenu: false
  sources:
    - 'section:18e01b2e-58fc-4c77-9e95-52cebfba80e8' # Blog Categories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
