contentColumnType: text
fieldGroup: a8521155-7afd-4462-b214-2c0909c7e927
handle: richText
instructions: ''
name: 'Rich Text'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: bb97edd2-4089-4569-baa6-15e309da1d3f # Standard
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
