contentColumnType: text
fieldGroup: f9938e69-64e4-4ea0-a405-767a320f556e
handle: role
instructions: ''
name: Role
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
