contentColumnType: text
fieldGroup: 73b82979-89d2-4e30-86ce-66e3493efdb0
handle: summary
instructions: ''
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
