defaultPlacement: end
enableVersioning: true
handle: client
name: Client
propagationMethod: all
siteSettings:
  e1df123e-aba9-482b-9ce4-52b0155cc872:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 294fa157-b347-4b56-bdc8-d7145c45a911
type: structure
