enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  e1df123e-aba9-482b-9ce4-52b0155cc872:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: contact
type: single
