enableVersioning: true
handle: playground
name: Playground
propagationMethod: all
siteSettings:
  e1df123e-aba9-482b-9ce4-52b0155cc872:
    enabledByDefault: true
    hasUrls: true
    template: playground/_entry
    uriFormat: 'playground/{slug}'
type: channel
