enableVersioning: true
handle: sampleWork
name: 'Sample Work'
propagationMethod: all
siteSettings:
  e1df123e-aba9-482b-9ce4-52b0155cc872:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: sample-work
type: single
