enableVersioning: true
handle: todayILearned
name: 'Today I Learned'
propagationMethod: all
siteSettings:
  e1df123e-aba9-482b-9ce4-52b0155cc872:
    enabledByDefault: true
    hasUrls: true
    template: today-i-learned/_entry
    uriFormat: 'today-i-learned/{slug}'
type: channel
